# Site settings
title:          Blog
description:    "Ali Behzadian's Blog"
url:            https://blog.behzadian.info

# Author
author:
  name:         Ali Behzadian Nejad
  email:        ali.behzadian@gmail.com
  url:          https://behzadian.info

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: ali.behzadian@gmail.com
  github: https://github.com/alibehzadian
  twitter: https://twitter.com/BehzadianAli
  linkedin: https://www.linkedin.com/in/ali-behzadian-nejad/
